/*
 * ebaymagapi
 * The application serves as the gateway to the internal synchronization module of eBayMag.  It offers Message APIs for external use and serves as the sole endpoint through which external applications can interact with the synchronization module..
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.saxu.bookcatalog.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum MessageOperationEnum {


  GET_BOOK_BY_ID("GET_BOOK_BY_ID"),

  CREATE_BOOK("CREATE_BOOK"),

  GET_BOOKS_BY_PAGE("GET_BOOKS_BY_PAGE"),

  UPDATE_BOOK("UPDATE_BOOK"),

  DELETE_BOOK("DELETE_BOOK");

  
  private String value;

  MessageOperationEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MessageOperationEnum fromValue(String text) {
    for (MessageOperationEnum b : MessageOperationEnum.values()) {
      if (String.valueOf(b.value).equals(String.valueOf(text))) {
        return b;
      }
    }
    return null;
  }

}
